{% set name = "docs-versions-menu" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docs_versions_menu-{{ version }}.tar.gz
  sha256: 8c6eae5836fb63e4f9700387385c5074dac8187609538422dab5fa39de110a73

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - docs-versions-menu = docs_versions_menu.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools

  run:
    - python >=3.7
    - jinja2
    - click >=6.7
    - packaging <22.0
    - pyparsing >=2.0.2
    - sphinx

test:
  imports:
    - docs_versions_menu
  requires:
    - pip
  commands:
    - docs-versions-menu --help
    - pip check

about:
  home: https://github.com/goerz/docs_versions_menu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A versions-menu for Sphinx-based documentation.
  doc_url: https://goerz.github.io/docs_versions_menu
  dev_url: https://github.com/goerz/docs_versions_menu

extra:
  recipe-maintainers:
    - hhslepicka
    - goerz
